#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
use_lua = 1
autocomplete_method = 'coc'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "bar"
statusline_iseparator = "bar"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true
# how project rooter are defined
project_rooter_patterns = [
  '.git/',
  '_darcs/',
  '.hg/',
  '.bzr/',
  '.svn/',
  '.vimspector.json',
]
project_rooter_outermost = false
# todo
todo_labels = ['FIXME', 'question', 'TODO', 'idea']
todo_prefix = '@'
# bootstraps
bootstrap_before = 'myspacevim#before'
bootstrap_after = 'myspacevim#after'
colorscheme = "nord"
# colorscheme_bg = "light"

[[layers]]
name = "colorscheme"

[[custom_plugins]]
# name = "dracula/vim"
repo = "kyoz/purify"
merged = 0

[[custom_plugins]]
repo = "gentoo/gentoo-syntax"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "git"

[[layers]]
name = "github"

[[custom_plugins]]
repo = "lilydjwg/colorizer"
merged = false

[[layers]]
name = "lang#latex"

[[layers]]
name = "format"

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true

[[layers]]
name = "debug"
debugger_plugin = "vimspector"

[[layers]]
name = "lang#cmake"

[[layers]]
name = "lang#julia"

[[layers]]
name = "sudo"

[[layers]]
name = 'lang#markdown'
enableWcwidth = 1
listItemIndent = 1
enabled_formater = ['prettier']

[[layers]]
name = 'checkers'
lint_on_the_fly = true
lint_on_save = true

[[layers]]
name = 'edit'
autosave_timeout = 300000
# autosave_events = ['InsertLeave', 'TextChanged']
autosave_all_buffers = true
enable_hop = false

[[layers]]
name = 'ui'
enable_scrollbar = true
enable_indentline = true
indentline_char = '│'
# filetree_show_hidden = true
cursorword_delay = 200
cursorword_exclude_filetype = ['markdown']
indentline_exclude_filetyps = ['startify', 'help']

[[layers]]
name = 'telescope'
enable = 'has("nvim")'

[[layers]]
name = 'lang#sh'
bash-file-head = [
  '#!/usr/bin/env bash',
  '# Time: `strftime("%Y-%m-%d %T")`',
  '',
]

[[layers]]
name = 'lang#python'
python_file_head = [
  '# -*- coding: utf-8 -*-',
  '# Author: Pppig236',
  '# Mail: umich.email@pppig236.com',
  '# Created Time: `strftime("%a %b %d")`',
  '',
]

[[layers]]
name = 'lang#toml'

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#typescript"

# enable lsp for cpp, typescript and vue
[[layers]]
name = 'lsp'
filetypes = ['c', 'cpp', 'typescript', 'vue', 'javascript', 'python']

# latex
[[custom_plugins]]
repo = "neoclide/coc-vimtex"

# typescript
[[custom_plugins]]
repo = "neoclide/coc-tsserver"
[[custom_plugins]]
repo = "neoclide/coc-eslint"

# Conflict marker
[[custom_plugins]]
repo = "rhysd/conflict-marker.vim"

# Copilot replacement
[[custom_plugins]]
repo = "Exafunction/codeium.vim"
